# Generated by Django 4.0.5 on 2022-10-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_hotels_img_hotels_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='pics')),
                ('name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
