# Generated by Django 4.0.5 on 2022-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_orders1_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('MobileNumber', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Indate', models.CharField(max_length=30)),
                ('Outdate', models.CharField(max_length=30)),
            ],
        ),
    ]
