# Generated by Django 4.0.5 on 2022-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mno', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('indate', models.CharField(max_length=30)),
                ('outdate', models.CharField(max_length=30)),
                ('room', models.CharField(max_length=10)),
            ],
        ),
    ]
