# Generated by Django 4.0.5 on 2022-11-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_foodorder_delete_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='RoomBook',
        ),
    ]
