# Generated by Django 4.0.5 on 2022-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_rename_room_roombook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mno', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('indate', models.CharField(max_length=30)),
                ('outdate', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomBook',
        ),
    ]
